name: buzhifanji blog
on: # on 字段指定触发 workflow 的条件，通常是某些事件
  push: # push事件触发 workflow
    branches: # 指定触发事件时，可以限定分支或标签
      - gh-pages

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/Buzhifanji'
          dst: 'gitee/buzhifanji'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          static_list: "blog"
          force_update: true
			    debug: true
